#! /bin/bash
FILES="CMakeFiles CMakeCache.txt cmake_install.cmake gmon.out \
CMakeLists.txt.user CTestTestfile.cmake Makefile Allocator.cbp"
flag=0
if [ -f Makefile ]
 then
	make clean;
	flag=1;
fi 
for file in $FILES
do
	if [ -f $file ] || [ -d $file ]
	 then
		rm -r $file; 
		flag=1;
	fi
done
if [[ $flag -eq 1 ]]
then 
	echo "Thanks for cleaning!"
else
	echo "There are nothing to delete yet."
fi
