# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/den/Allocator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/den/Allocator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/den/Allocator/CMakeFiles /home/den/Allocator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/den/Allocator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Allocator

# Build rule for target.
Allocator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Allocator
.PHONY : Allocator

# fast build rule for target.
Allocator/fast:
	$(MAKE) -f CMakeFiles/Allocator.dir/build.make CMakeFiles/Allocator.dir/build
.PHONY : Allocator/fast

#=============================================================================
# Target rules for targets named test1

# Build rule for target.
test1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test1
.PHONY : test1

# fast build rule for target.
test1/fast:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/build
.PHONY : test1/fast

#=============================================================================
# Target rules for targets named test2

# Build rule for target.
test2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test2
.PHONY : test2

# fast build rule for target.
test2/fast:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/build
.PHONY : test2/fast

src/heap.o: src/heap.cpp.o
.PHONY : src/heap.o

# target to build an object file
src/heap.cpp.o:
	$(MAKE) -f CMakeFiles/Allocator.dir/build.make CMakeFiles/Allocator.dir/src/heap.cpp.o
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/heap.cpp.o
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/heap.cpp.o
.PHONY : src/heap.cpp.o

src/heap.i: src/heap.cpp.i
.PHONY : src/heap.i

# target to preprocess a source file
src/heap.cpp.i:
	$(MAKE) -f CMakeFiles/Allocator.dir/build.make CMakeFiles/Allocator.dir/src/heap.cpp.i
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/heap.cpp.i
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/heap.cpp.i
.PHONY : src/heap.cpp.i

src/heap.s: src/heap.cpp.s
.PHONY : src/heap.s

# target to generate assembly for a file
src/heap.cpp.s:
	$(MAKE) -f CMakeFiles/Allocator.dir/build.make CMakeFiles/Allocator.dir/src/heap.cpp.s
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/heap.cpp.s
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/heap.cpp.s
.PHONY : src/heap.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Allocator.dir/build.make CMakeFiles/Allocator.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Allocator.dir/build.make CMakeFiles/Allocator.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Allocator.dir/build.make CMakeFiles/Allocator.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mm.o: src/mm.cpp.o
.PHONY : src/mm.o

# target to build an object file
src/mm.cpp.o:
	$(MAKE) -f CMakeFiles/Allocator.dir/build.make CMakeFiles/Allocator.dir/src/mm.cpp.o
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/mm.cpp.o
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/mm.cpp.o
.PHONY : src/mm.cpp.o

src/mm.i: src/mm.cpp.i
.PHONY : src/mm.i

# target to preprocess a source file
src/mm.cpp.i:
	$(MAKE) -f CMakeFiles/Allocator.dir/build.make CMakeFiles/Allocator.dir/src/mm.cpp.i
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/mm.cpp.i
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/mm.cpp.i
.PHONY : src/mm.cpp.i

src/mm.s: src/mm.cpp.s
.PHONY : src/mm.s

# target to generate assembly for a file
src/mm.cpp.s:
	$(MAKE) -f CMakeFiles/Allocator.dir/build.make CMakeFiles/Allocator.dir/src/mm.cpp.s
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/mm.cpp.s
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/mm.cpp.s
.PHONY : src/mm.cpp.s

src/thread_safe_mm.o: src/thread_safe_mm.cpp.o
.PHONY : src/thread_safe_mm.o

# target to build an object file
src/thread_safe_mm.cpp.o:
	$(MAKE) -f CMakeFiles/Allocator.dir/build.make CMakeFiles/Allocator.dir/src/thread_safe_mm.cpp.o
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/thread_safe_mm.cpp.o
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/thread_safe_mm.cpp.o
.PHONY : src/thread_safe_mm.cpp.o

src/thread_safe_mm.i: src/thread_safe_mm.cpp.i
.PHONY : src/thread_safe_mm.i

# target to preprocess a source file
src/thread_safe_mm.cpp.i:
	$(MAKE) -f CMakeFiles/Allocator.dir/build.make CMakeFiles/Allocator.dir/src/thread_safe_mm.cpp.i
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/thread_safe_mm.cpp.i
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/thread_safe_mm.cpp.i
.PHONY : src/thread_safe_mm.cpp.i

src/thread_safe_mm.s: src/thread_safe_mm.cpp.s
.PHONY : src/thread_safe_mm.s

# target to generate assembly for a file
src/thread_safe_mm.cpp.s:
	$(MAKE) -f CMakeFiles/Allocator.dir/build.make CMakeFiles/Allocator.dir/src/thread_safe_mm.cpp.s
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/src/thread_safe_mm.cpp.s
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/src/thread_safe_mm.cpp.s
.PHONY : src/thread_safe_mm.cpp.s

test1.o: test1.cpp.o
.PHONY : test1.o

# target to build an object file
test1.cpp.o:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/test1.cpp.o
.PHONY : test1.cpp.o

test1.i: test1.cpp.i
.PHONY : test1.i

# target to preprocess a source file
test1.cpp.i:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/test1.cpp.i
.PHONY : test1.cpp.i

test1.s: test1.cpp.s
.PHONY : test1.s

# target to generate assembly for a file
test1.cpp.s:
	$(MAKE) -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/test1.cpp.s
.PHONY : test1.cpp.s

test2.o: test2.cpp.o
.PHONY : test2.o

# target to build an object file
test2.cpp.o:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/test2.cpp.o
.PHONY : test2.cpp.o

test2.i: test2.cpp.i
.PHONY : test2.i

# target to preprocess a source file
test2.cpp.i:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/test2.cpp.i
.PHONY : test2.cpp.i

test2.s: test2.cpp.s
.PHONY : test2.s

# target to generate assembly for a file
test2.cpp.s:
	$(MAKE) -f CMakeFiles/test2.dir/build.make CMakeFiles/test2.dir/test2.cpp.s
.PHONY : test2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Allocator"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... test1"
	@echo "... test2"
	@echo "... src/heap.o"
	@echo "... src/heap.i"
	@echo "... src/heap.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mm.o"
	@echo "... src/mm.i"
	@echo "... src/mm.s"
	@echo "... src/thread_safe_mm.o"
	@echo "... src/thread_safe_mm.i"
	@echo "... src/thread_safe_mm.s"
	@echo "... test1.o"
	@echo "... test1.i"
	@echo "... test1.s"
	@echo "... test2.o"
	@echo "... test2.i"
	@echo "... test2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

